Ver esterno stesura
DPCMGroup/dpcm2077-docs pull request #125
Opened 2021-06-01 15:14 UTC by DanieleSpigolon

2021-06-02 10:13 UTC, antobaddo requested changes
solo 2 modifiche veloci da fare

2021-06-02 10:13 UTC, antobaddo commented on esterni/verbali/VE_2021_06_01/res/contenuto.tex
> +\subsection*{Presentazione demo intermedia a Imola Informatica in vista del collaudo}
toglierei intermedia

2021-06-02 10:13 UTC, antobaddo commented on esterni/verbali/VE_2021_06_01/res/tracciamenti.tex
> +	VE\_2021-06-01\_1 & Si è deciso di mostrare una demo intermedia a Imola Informatica \\
toglierei intermedia

2021-06-02 10:38 UTC, DanieleSpigolon commented
@ToldoDM puoi approvare

2021-06-03 09:05 UTC, antobaddo approved these changes

2021-06-03 14:30 UTC, merged